---
apiVersion: v1
kind: Pod
metadata:
  name: multi-container-with-emptydir-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /var/empty-dir-volume
          name: empty-dir-volume
    - name: debian
      image: debian
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 30; done;"] # prevents container from exiting after completion
      volumeMounts:
        - mountPath: /var/empty-dir-volume
          name: empty-dir-volume
  volumes:
    - name: empty-dir-volume
      emptyDir: {}
