apiVersion: v1
kind: Pod
metadata:
  name: nginx-debian-with-custom-commands
spec:
  restartPolicy: Never
  containers:
    - name: nginx
      image: nginx:latest
    - name: debian
      image: debian
      command: ["sleep"] # corresponds to docker's ENTRYPOINT
      args: ["60"] # corresponds to docker's CMD
