---
- name: Fetch join command from master
  slurp:
    src: "/etc/kubernetes/join-cmd.sh"
  delegate_to: "{{ groups['control'][0] }}"
  run_once: true
  register: join_cmd

- name: Join the cluster
  shell: "{{ join_cmd.content | b64decode }}"
...
